spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/kanionland_user
    username: kanionland
    password: kanionland123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE